FROM golang:1.16 as build

RUN apt-get update && apt-get install -y ninja-build

# TODO: Змініть на власну реалізацію системи збірки
WORKDIR /go/src
RUN git clone https://github.com/KabirLabibIP84/lab2
WORKDIR /go/src/se-lab1
RUN go get -u ./build/cmd/bood

WORKDIR /go/src/se-lab2
COPY . .

# TODO: Замініть на запуск bood, який призводить до виконання інтеграційних тестів.
# ENTRYPOINT ["echo", "ok"]

WORKDIR /go/src/se-lab2/integration

ENTRYPOINT bood 2>&1 | tee integration.log

